#!/bin/bash

set -e

TAR="${TAR:-tar}"
ref="$1" # HEAD or tag
prefix_path="pkg"
os="darwin"
arch="amd64"
package='mackerel-plugin-macbook-battery-health'
version="$(git describe --abbrev=0 --tags --always $ref)"
src_path="${package}_${os}_${arch}/"
archive_path="${package}_${os}_${arch}.zip"

echo "---> Create release for $version" >&2
git archive --prefix "$src_path" --format=tar "$ref" | "$TAR" -C . -xf -
zip -r "$archive_path" "$src_path"
